"""
Python variables that we need to change for every reduction run. 

1) Copy and edit this file
2) start casa
3) then run `execfile("config.py")`
"""

verbose = True # set to true for extra print statements

###################################################
#### FOR NAMING INTERMEDIATE FILES ################
###################################################
# the observation date
# THIS DATE MUST BE IN THE FORM 'mon-dd-yyy' (ex. 'mar-29-2025')
date='somedate'

# the observation band 
band='someband'

# the existing basenames for the files
basename=["uid___A002_Xd81670_X867e","uid___A002_Xd81670_X8a51","uid___A002_Xd81670_X8d91"]

###################################################
#### FIELD NAMES IN THE DATASET  ##################
###################################################
fieldnames = ['J0423-0120','J0348-2749','GRB_pol']
tsysfields_self = ['J0423-0120','GRB_pol']
tsysfields_alt  = ['J0348-2749']
tsysfields_ref  = {'J0348-2749':'J0423-0120'}

###################################################
#### THE SPW MAP FOR THE FILES ####################
###################################################
spw0={"uid___A002_Xd81670_X867e":'13,15,17,19',"uid___A002_Xd81670_X8a51":'13,15,17,19',"uid___A002_Xd81670_X8d91":'5,7,9,11'}
# science spw numbers in the concatenated ms (determine using listobs after concat ends)
sciencespw='13,15,17,19'
spwmax = 20 # Highest spectral window number in dataset

###################################################
#### CONTROLS FOR THE SCRIPT ######################
###################################################

# set to true if you need to run importasdm
doimport     = False

# set to true if you want to run listobs and save a text file with the result
dolistobs    = False

# set to true if you want to do the apriori flagging of the ms files
aprioriflags = False

# set to true to run fixsyscaltimes
dofixsyscaltimes = False

# set to true if you want to calibrate the data
docalibrate      = False
dogencal         = False
doapplycal       = False

# set to true if you want to overwrite the existing Tsys and WVR tables
clobberTsysTable = False
clobberWVRTable  = False

# set to true if you want to concat and split the data
doconcat         = False
dosplit          = False


###################################################
####### FIELD NAMES/NUMBERS FOR CALIBRATION #######
###################################################
# Run listobs after the last pre-cal step concludes
# to set the values here for calibrate.py

Lcal = 'Polcal'       # LEAKAGE CALIBRATOR
Fcal = 'Fluxcal'      # FLUX CALIBRATOR
Bcal = 'Bandpass'     # BANDPASS CALIBRATOR
Gcal = 'Gaincal'      # COMPLEX GAIN CALIBRATOR
Trgt = 'Target'       # TARGET
refant = 'DA43'       # Reference antenna
polscan = None        # Best scan to use for deriving cross-hand delays, e.g. '48'
target_chan_avg = 1   # Can average calibrated targed data in frequency
ms_to_calibrate = date+'_'+band+'.ms' # Name of final ms generated by alma_precal.py (should not need to be changed)
ms_to_split_target = Trgt+'.pol.cal.ms'
ms_to_split_Gcal = Gcal+'.pol.cal.ms'
ms_to_split_Lcal = Lcal+'.pol.cal.ms'

# Parallel-hand calibration
docal_SetJy            = False 
docal_Bandpass         = False 
docal_Gain             = False
docal_Fluxscale        = False
applycal_ParallelHand  = False # Apply parallel hand calibration to bandpass, flux, and gain calibrators
# Polarization calibration    # These steps are performed on the leakage calibrator
dopol_Gain             = False # Derive preliminary gain solutions on leakage calibrator
dopol_ApplyGainBP      = False # Apply time-varying gains and bandpass to leakage calibrator
dopol_QU               = False # Estimate the linear polarization of the leakage calibrator
dopol_CrossHandDelay   = False # Derive the instrumental cross-hand delay using scan #polscan (must be not none)
dopol_ApplyKcrs        = False # Apply cross-hand delays to leakage calibrator
dopol_XYphase          = False # Calibrate XY phase
dopol_ApplyXYphase     = False # Apply XY phase calibration to leakage calibrator
dopol_RegenLcalGains   = False # Derive final gain solutions on leakage calibrator
dopol_Leakage          = False # Derive instrumental polarization leakage
dopol_XYamp            = False # Derive X/Y amplitude ratio
applycal_Lcal          = False # Apply all calibrations to leakage calibrator
# Final applycals and splits
applycal_Trgt          = False # Apply all calibrations to gain calibrator and target
dosplit_Target         = False # Split off target data
dosplit_Gcal           = False # Split off target data
dosplit_Lcal           = False # Split off target data
